import { useState, useEffect, useCallback, useRef } from "react";
import { supabase } from "@/integrations/supabase/client";
import { convertToWebP } from "@/lib/imageUtils";
import {
  Upload,
  Search,
  Check,
  X,
  Trash2,
  ImageIcon,
  Loader2,
  CheckSquare,
  Square,
  Copy,
  Wand2,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const ALLOWED_TYPES = ["image/jpeg", "image/png", "image/webp"];
const MAX_FILE_SIZE = 10 * 1024 * 1024;
const BRANDED_DOMAIN = "https://verifiedbm.shop";
const LOCAL_MEDIA_API = "/media-local.php";

/** Force lowercase, replace spaces/underscores with hyphens, strip non-web-safe chars */
const toWebSafeSlug = (val: string): string =>
  val
    .toLowerCase()
    .replace(/\.webp$/i, "")
    .replace(/\s+/g, "-")
    .replace(/_/g, "-")
    .replace(/[^a-z0-9\-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

/** Plain text identifier: lowercase, spaces preserved, no extension */
const toPlainName = (val: string): string =>
  val
    .toLowerCase()
    .replace(/\.webp$/i, "")
    .replace(/[-_]+/g, " ")
    .replace(/[^a-z0-9 ]/g, "")
    .replace(/\s+/g, " ")
    .trim();

export interface MediaFile {
  id: string;
  file_name: string;
  file_path: string;
  file_size: number;
  mime_type: string;
  width: number | null;
  height: number | null;
  alt_text: string;
  caption: string;
  description?: string;
  url: string;
  url_slug: string | null;
  created_at: string;
}

interface UploadingFile {
  id: string;
  name: string;
  progress: number;
}

interface PendingFile {
  id: string;
  originalFile: File;
  webpFile: File;
  previewUrl: string;
  fileName: string; // internal plain text name
  urlSlug: string;  // SEO-friendly public slug with .webp
  altText: string;
  caption: string;
  imageDetails: string; // long-form metadata
  dimensions: { width: number; height: number };
}

interface MediaLibraryProps {
  mode?: "page" | "modal";
  onSelect?: (file: MediaFile) => void;
  uploadPathPrefix?: string;
}

const formatFileSize = (bytes: number) => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

/** Sidebar with full metadata editing */
const FileDetailsSidebar = ({
  file,
  onSave,
  onClose,
  onDelete,
  onSelect,
  mode,
}: {
  file: MediaFile;
  onSave: (id: string, data: Partial<MediaFile>) => Promise<void>;
  onClose: () => void;
  onDelete: (id: string) => void;
  onSelect?: (f: MediaFile) => void;
  mode: "page" | "modal";
}) => {
  const [urlSlug, setUrlSlug] = useState(file.url_slug || "");
  const [altText, setAltText] = useState(file.alt_text || "");
  const [caption, setCaption] = useState(file.caption || "");
  const [description, setDescription] = useState((file as any).description || "");
  const [saving, setSaving] = useState(false);
  const [aiFixing, setAiFixing] = useState<string | null>(null);

  useEffect(() => {
    setUrlSlug(file.url_slug || "");
    setAltText(file.alt_text || "");
    setCaption(file.caption || "");
    setDescription((file as any).description || "");
  }, [file.id]);

  const slugForUrl = urlSlug.includes(".webp") ? urlSlug : (urlSlug ? toWebSafeSlug(urlSlug) + ".webp" : "");
  const brandedUrl = `${BRANDED_DOMAIN}/media/${slugForUrl || file.file_name}`;

  const handleSave = async () => {
    setSaving(true);
    const safeSlug = toWebSafeSlug(urlSlug);
    const slugWithExt = safeSlug ? safeSlug + ".webp" : "";
    const finalAlt = altText.trim() || safeSlug.replace(/-/g, " ");
    await onSave(file.id, {
      url_slug: slugWithExt || null,
      alt_text: finalAlt,
      caption,
      ...({ description } as any),
    } as any);
    setUrlSlug(slugWithExt);
    setSaving(false);
    toast.success("Metadata saved!");
  };

  const handleAIFix = async (action: "fix_alt_text" | "fix_image_details") => {
    setAiFixing(action);
    try {
      const { data: result, error } = await supabase.functions.invoke("seo-ai-fix", {
        body: {
          action,
          context: {
            fileName: file.file_name,
            currentAltText: altText,
            focusKeyword: altText || file.file_name,
          },
        },
      });
      if (error) throw error;
      if (result?.error) { toast.error(result.error); return; }

      if (action === "fix_alt_text" && result?.altText) {
        setAltText(result.altText);
        toast.success("Alt text generated by AI!");
      } else if (action === "fix_image_details" && result?.imageDetails) {
        setDescription(result.imageDetails);
        toast.success("Image details generated by AI!");
      }
    } catch (err) {
      console.error("AI fix error:", err);
      toast.error("AI fix failed. Try again.");
    } finally {
      setAiFixing(null);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-foreground">File Details</h3>
        <button onClick={onClose} className="p-1 rounded hover:bg-accent text-muted-foreground">
          <X className="w-4 h-4" />
        </button>
      </div>

      <img
        src={file.url}
        alt={file.alt_text || file.file_name}
        className="w-full rounded-lg border border-border object-contain max-h-48"
      />

      {/* Info row */}
      <div className="space-y-1.5 text-sm">
        {file.width && file.height && (
          <div className="flex justify-between">
            <span className="text-muted-foreground">Dimensions</span>
            <span className="text-foreground">{file.width} × {file.height}</span>
          </div>
        )}
        <div className="flex justify-between">
          <span className="text-muted-foreground">Size</span>
          <span className="text-foreground">{formatFileSize(file.file_size)}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-muted-foreground">Type</span>
          <span className="text-foreground">{file.mime_type}</span>
        </div>
      </div>

      <div className="space-y-3">
        {/* Internal File Name */}
        <div>
          <label className="text-xs font-medium text-muted-foreground mb-1 block">Internal File Name</label>
          <Input value={file.file_name} readOnly className="text-sm h-8 bg-muted cursor-not-allowed" />
          <p className="text-[10px] text-muted-foreground mt-0.5">Plain text identifier — locked after upload</p>
        </div>

        {/* URL Slug */}
        <div>
          <label className="text-xs font-medium text-muted-foreground mb-1 block">Public URL Slug</label>
          <Input
            value={urlSlug}
            onChange={(e) => setUrlSlug(e.target.value)}
            placeholder={toWebSafeSlug(file.file_name) + ".webp"}
            className="text-sm h-8 font-mono"
          />
          <p className="text-[10px] text-muted-foreground mt-0.5">
            Branded URL: {brandedUrl}
          </p>
        </div>

        {/* Alt Text with AI button */}
        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-xs font-medium text-muted-foreground">Alt Text</label>
            <button
              onClick={() => handleAIFix("fix_alt_text")}
              disabled={!!aiFixing}
              className="flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded bg-primary/10 text-primary hover:bg-primary/20 disabled:opacity-50 transition-colors"
            >
              {aiFixing === "fix_alt_text" ? <Loader2 className="w-3 h-3 animate-spin" /> : <Wand2 className="w-3 h-3" />}
              AI
            </button>
          </div>
          <Input value={altText} onChange={(e) => setAltText(e.target.value)} placeholder="SEO & accessibility text…" className="text-sm h-8" />
        </div>

        <div>
          <label className="text-xs font-medium text-muted-foreground mb-1 block">Caption</label>
          <Input value={caption} onChange={(e) => setCaption(e.target.value)} placeholder="Text below the image…" className="text-sm h-8" />
        </div>

        {/* Image Details with AI button */}
        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-xs font-medium text-muted-foreground">Image Details</label>
            <button
              onClick={() => handleAIFix("fix_image_details")}
              disabled={!!aiFixing}
              className="flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded bg-primary/10 text-primary hover:bg-primary/20 disabled:opacity-50 transition-colors"
            >
              {aiFixing === "fix_image_details" ? <Loader2 className="w-3 h-3 animate-spin" /> : <Wand2 className="w-3 h-3" />}
              AI
            </button>
          </div>
          <Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Long-form metadata, e.g. 'Account created in 2023 with $500 daily spending limit and full document verification'" rows={4} className="text-sm" />
          <p className="text-[10px] text-muted-foreground mt-0.5">Used for Schema.org image metadata</p>
        </div>
      </div>

      <Button className="w-full gap-2" onClick={handleSave} disabled={saving}>
        {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
        Save Metadata
      </Button>

      {mode === "modal" && onSelect && (
        <Button variant="outline" className="w-full" onClick={() => onSelect(file)}>Select Image</Button>
      )}

      <Button variant="outline" size="sm" className="w-full gap-2" onClick={() => { navigator.clipboard.writeText(brandedUrl); toast.success("Branded URL copied!"); }}>
        <Copy className="w-3.5 h-3.5" /> Copy Branded URL
      </Button>

      <Button variant="destructive" size="sm" className="w-full gap-2" onClick={() => onDelete(file.id)}>
        <Trash2 className="w-3.5 h-3.5" /> Delete Permanently
      </Button>
    </div>
  );
};

const MediaLibrary = ({ mode = "page", onSelect, uploadPathPrefix = "" }: MediaLibraryProps) => {
  const [files, setFiles] = useState<MediaFile[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [bulkMode, setBulkMode] = useState(false);
  const [bulkSelected, setBulkSelected] = useState<Set<string>>(new Set());
  const [uploading, setUploading] = useState<UploadingFile[]>([]);
  const [pendingFiles, setPendingFiles] = useState<PendingFile[]>([]);
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);
  const [bulkDeleteOpen, setBulkDeleteOpen] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const dropRef = useRef<HTMLDivElement>(null);
  const [dragOver, setDragOver] = useState(false);
  const [bulkFixing, setBulkFixing] = useState(false);

  const updateLocalMetadata = async (id: string, data: Partial<MediaFile>) => {
    const response = await fetch(`${LOCAL_MEDIA_API}?action=update`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, data }),
    });
    if (!response.ok) throw new Error("Failed to update media metadata.");
  };

  const fetchFiles = useCallback(async () => {
    setLoading(true);
    try {
      const response = await fetch(`${LOCAL_MEDIA_API}?action=list`, { cache: "no-store" });
      if (!response.ok) throw new Error("Failed to fetch local media files.");
      const payload = await response.json();
      setFiles(Array.isArray(payload.files) ? (payload.files as MediaFile[]) : []);
    } catch {
      setFiles([]);
      toast.error("Media API unavailable. Ensure media-local.php is enabled on your server.");
    }
    setLoading(false);
  }, []);

  useEffect(() => { fetchFiles(); }, [fetchFiles]);

  const handleBulkSEOFix = async () => {
    const needsFix = files.filter((f) => !f.alt_text?.trim() || !f.url_slug?.trim());
    if (needsFix.length === 0) { toast.info("All images already have alt text and slugs!"); return; }

    setBulkFixing(true);
    try {
      const { data: result, error } = await supabase.functions.invoke("seo-ai-fix", {
        body: {
          action: "bulk_media_fix",
          context: {
            images: needsFix.slice(0, 20).map((f) => ({
              id: f.id,
              fileName: f.file_name,
              altText: f.alt_text || "",
              urlSlug: f.url_slug || "",
            })),
          },
        },
      });

      if (error) throw error;
      if (result?.error) { toast.error(result.error); return; }
      if (result?.fixes) {
        let fixed = 0;
        for (const fix of result.fixes) {
          const file = needsFix.find((f) => f.id === fix.id);
          if (!file) continue;
          const safeSlug = fix.urlSlug?.endsWith(".webp") ? fix.urlSlug : (fix.urlSlug ? toWebSafeSlug(fix.urlSlug.replace(/\.webp$/, "")) + ".webp" : file.url_slug);
          await updateLocalMetadata(fix.id, {
            alt_text: fix.altText || file.alt_text,
            url_slug: safeSlug || file.url_slug,
          });
          fixed++;
        }
        toast.success(`Fixed SEO for ${fixed} images!`);
        fetchFiles();
      }
    } catch (err) {
      console.error("Bulk SEO fix error:", err);
      toast.error("Bulk fix failed. Try again.");
    } finally {
      setBulkFixing(false);
    }
  };

  const selectedFile = files.find((f) => f.id === selectedId) || null;

  const getImageDimensions = (file: File): Promise<{ width: number; height: number }> =>
    new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
      img.onerror = () => resolve({ width: 0, height: 0 });
      img.src = URL.createObjectURL(file);
    });

  /** Stage files for pending review */
  const stageFiles = async (fileList: FileList | File[]) => {
    const arr = Array.from(fileList);
    for (const originalFile of arr) {
      if (!ALLOWED_TYPES.includes(originalFile.type)) {
        toast.error(`"${originalFile.name}" is not allowed. Only JPG, PNG, and WebP.`);
        continue;
      }
      if (originalFile.size > MAX_FILE_SIZE) {
        toast.error(`"${originalFile.name}" exceeds the 10MB limit.`);
        continue;
      }
      const webpFile = await convertToWebP(originalFile, 0.8);
      const dims = await getImageDimensions(webpFile);
      const baseName = originalFile.name.replace(/\.[^.]+$/, "");
      const plainName = toPlainName(baseName);
      const slug = toWebSafeSlug(baseName) + ".webp";
      const storagePath = toWebSafeSlug(baseName) + ".webp";
      const previewUrl = URL.createObjectURL(webpFile);
      setPendingFiles((prev) => [
        ...prev,
        {
          id: crypto.randomUUID(),
          originalFile,
          webpFile,
          previewUrl,
          fileName: plainName,
          urlSlug: slug,
          altText: plainName,
          caption: "",
          imageDetails: "",
          dimensions: dims,
        },
      ]);
    }
  };

  const updatePendingField = (id: string, field: keyof PendingFile, value: string) => {
    setPendingFiles((prev) =>
      prev.map((p) => {
        if (p.id !== id) return p;
        const updated = { ...p, [field]: value };
        // When URL slug changes, auto-fill alt text from slug (without .webp)
        if (field === "urlSlug") {
          const cleanSlug = toWebSafeSlug(value);
          updated.altText = cleanSlug.replace(/-/g, " ");
        }
        return updated;
      })
    );
  };

  const removePending = (id: string) => {
    setPendingFiles((prev) => {
      const item = prev.find((p) => p.id === id);
      if (item) URL.revokeObjectURL(item.previewUrl);
      return prev.filter((p) => p.id !== id);
    });
  };

  /** Confirm and upload a single pending file */
  const confirmUpload = async (pending: PendingFile) => {
    const uploadId = pending.id;
    // URL slug with .webp is used as the storage path
    const safeSlug = pending.urlSlug.endsWith(".webp")
      ? toWebSafeSlug(pending.urlSlug.replace(/\.webp$/, "")) + ".webp"
      : toWebSafeSlug(pending.urlSlug) + ".webp";
    const cleanPrefix = uploadPathPrefix.replace(/^\/+|\/+$/g, "");
    const storagePath = cleanPrefix ? `${cleanPrefix}/${safeSlug}` : safeSlug;
    const plainName = pending.fileName; // plain text internal name

    setUploading((prev) => [...prev, { id: uploadId, name: plainName, progress: 30 }]);
    removePending(pending.id);

    try {
      setUploading((prev) => prev.map((u) => (u.id === uploadId ? { ...u, progress: 50 } : u)));

      const formData = new FormData();
      formData.append("file", pending.webpFile, safeSlug);
      formData.append("pathPrefix", cleanPrefix);
      formData.append("slug", safeSlug);
      formData.append("fileName", plainName);
      formData.append("altText", pending.altText.trim() || toWebSafeSlug(pending.urlSlug).replace(/-/g, " "));
      formData.append("caption", pending.caption);
      formData.append("description", pending.imageDetails);
      formData.append("width", String(pending.dimensions.width || 0));
      formData.append("height", String(pending.dimensions.height || 0));

      const uploadResponse = await fetch(`${LOCAL_MEDIA_API}?action=upload`, {
        method: "POST",
        body: formData,
      });

      if (!uploadResponse.ok) throw new Error("Upload failed");

      setUploading((prev) => prev.map((u) => (u.id === uploadId ? { ...u, progress: 80 } : u)));

      const uploadPayload = await uploadResponse.json();
      if (uploadPayload?.file) {
        setFiles((prev) => [uploadPayload.file as MediaFile, ...prev]);
      }

      setUploading((prev) => prev.map((u) => (u.id === uploadId ? { ...u, progress: 100 } : u)));
      setTimeout(() => setUploading((prev) => prev.filter((u) => u.id !== uploadId)), 500);

      toast.success(`"${plainName}" uploaded successfully.`);
    } catch (err: any) {
      toast.error(`Failed to upload "${plainName}".`);
      setUploading((prev) => prev.filter((u) => u.id !== uploadId));
    }
  };

  const confirmAllPending = async () => {
    const toUpload = [...pendingFiles];
    for (const p of toUpload) await confirmUpload(p);
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const fileList = e.target.files;
    if (!fileList) return;
    stageFiles(fileList);
    e.target.value = "";
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    stageFiles(e.dataTransfer.files);
  };

  const handleDelete = async (id: string) => {
    const response = await fetch(`${LOCAL_MEDIA_API}?action=delete`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id }),
    });
    if (!response.ok) {
      toast.error("Failed to delete file.");
      return;
    }
    setFiles((prev) => prev.filter((f) => f.id !== id));
    if (selectedId === id) setSelectedId(null);
    setDeleteTarget(null);
    toast.success("File deleted.");
  };

  const handleBulkDelete = async () => {
    const ids = Array.from(bulkSelected);
    const response = await fetch(`${LOCAL_MEDIA_API}?action=delete`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ids }),
    });
    if (!response.ok) {
      toast.error("Failed to delete selected files.");
      return;
    }
    setFiles((prev) => prev.filter((f) => !bulkSelected.has(f.id)));
    setBulkSelected(new Set());
    setBulkDeleteOpen(false);
    setBulkMode(false);
    setSelectedId(null);
    toast.success(`${ids.length} file(s) deleted.`);
  };

  const saveFileMetadata = async (id: string, data: Partial<MediaFile>) => {
    await updateLocalMetadata(id, data);
    setFiles((prev) => prev.map((f) => (f.id === id ? { ...f, ...data } : f)));
  };

  const toggleBulkSelect = (id: string) => {
    setBulkSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const filteredFiles = files.filter((f) => {
    const q = search.toLowerCase();
    return f.file_name.toLowerCase().includes(q) || (f.url_slug || "").toLowerCase().includes(q);
  });

  const isCompact = mode === "modal";

  return (
    <div className={cn("flex flex-col lg:flex-row gap-6", isCompact && "h-full")}>
      {/* Main Area */}
      <div className="flex-1 space-y-4 min-w-0">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          {!isCompact && <h2 className="text-2xl font-bold text-foreground">Media Library</h2>}
          <div className="flex items-center gap-2 w-full sm:w-auto">
            <Button onClick={() => fileInputRef.current?.click()} className="gap-2" size={isCompact ? "sm" : "default"}>
              <Upload className="w-4 h-4" /> Upload New
            </Button>
            <Button
              variant={bulkMode ? "default" : "outline"}
              size={isCompact ? "sm" : "default"}
              onClick={() => { setBulkMode((b) => !b); setBulkSelected(new Set()); }}
              className="gap-2"
            >
              <CheckSquare className="w-4 h-4" />
              <span className="hidden sm:inline">Bulk Select</span>
            </Button>
            <Button
              variant="outline"
              size={isCompact ? "sm" : "default"}
              onClick={handleBulkSEOFix}
              disabled={bulkFixing}
              className="gap-2"
            >
              {bulkFixing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              <span className="hidden sm:inline">Auto-Fix All SEO</span>
            </Button>
            {bulkMode && bulkSelected.size > 0 && (
              <Button variant="destructive" size={isCompact ? "sm" : "default"} onClick={() => setBulkDeleteOpen(true)} className="gap-2">
                <Trash2 className="w-4 h-4" /> Delete ({bulkSelected.size})
              </Button>
            )}
          </div>
        </div>

        {/* Search */}
        <div className="relative max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by name or slug…" className="pl-9" />
        </div>

        <input ref={fileInputRef} type="file" accept=".jpg,.jpeg,.png,.webp" multiple className="hidden" onChange={handleFileSelect} />

        {/* Pending Uploads */}
        {pendingFiles.length > 0 && (
          <div className="space-y-3 rounded-xl border border-primary/30 bg-primary/5 p-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold text-foreground">Pending Uploads — Edit Before Confirming</h3>
              <div className="flex gap-2">
                <Button size="sm" variant="outline" onClick={() => { pendingFiles.forEach((p) => URL.revokeObjectURL(p.previewUrl)); setPendingFiles([]); }}>
                  <X className="w-3.5 h-3.5 mr-1" /> Cancel All
                </Button>
                <Button size="sm" onClick={confirmAllPending}>
                  <Check className="w-3.5 h-3.5 mr-1" /> Confirm All
                </Button>
              </div>
            </div>
            {pendingFiles.map((p) => (
              <div key={p.id} className="flex gap-4 items-start bg-background rounded-lg border border-border p-3">
                <img src={p.previewUrl} alt="Preview" className="w-20 h-20 rounded-md object-cover shrink-0 border border-border" />
                <div className="flex-1 space-y-2 min-w-0">
                  <div>
                    <label className="text-xs font-medium text-muted-foreground">Internal File Name (plain text)</label>
                    <Input
                      value={p.fileName}
                      onChange={(e) => updatePendingField(p.id, "fileName", e.target.value)}
                      className="text-sm h-8"
                    />
                    <p className="text-[10px] text-muted-foreground">Plain text identifier — no extension needed</p>
                  </div>
                  <div>
                    <label className="text-xs font-medium text-muted-foreground">Public URL Slug (.webp)</label>
                    <Input
                      value={p.urlSlug}
                      onChange={(e) => updatePendingField(p.id, "urlSlug", e.target.value)}
                      className="text-sm h-8 font-mono"
                    />
                    <p className="text-[10px] text-muted-foreground">
                      Branded URL: {BRANDED_DOMAIN}/media/{p.urlSlug.endsWith(".webp") ? toWebSafeSlug(p.urlSlug.replace(/\.webp$/, "")) + ".webp" : toWebSafeSlug(p.urlSlug) + ".webp"}
                    </p>
                  </div>
                  <div>
                    <label className="text-xs font-medium text-muted-foreground">Alt Text</label>
                    <Input value={p.altText} onChange={(e) => updatePendingField(p.id, "altText", e.target.value)} placeholder="SEO & accessibility" className="text-sm h-8" />
                  </div>
                  <div>
                    <label className="text-xs font-medium text-muted-foreground">Caption</label>
                    <Input value={p.caption} onChange={(e) => updatePendingField(p.id, "caption", e.target.value)} placeholder="Optional caption" className="text-sm h-8" />
                  </div>
                  <div>
                    <label className="text-xs font-medium text-muted-foreground">Image Details</label>
                    <Textarea value={p.imageDetails} onChange={(e) => updatePendingField(p.id, "imageDetails", e.target.value)} placeholder="Long-form metadata, e.g. 'Account created in 2023 with $500 daily spending limit...'" rows={2} className="text-sm" />
                  </div>
                  <div className="flex gap-2 pt-1">
                    <Button size="sm" onClick={() => confirmUpload(p)} className="gap-1">
                      <Upload className="w-3.5 h-3.5" /> Confirm Upload
                    </Button>
                    <Button size="sm" variant="ghost" onClick={() => removePending(p.id)}>
                      <X className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Grid */}
        <div
          ref={dropRef}
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={handleDrop}
          className={cn(
            "rounded-xl border-2 border-dashed transition-colors min-h-[200px]",
            dragOver ? "border-primary bg-primary/5" : "border-transparent"
          )}
        >
          {loading ? (
            <div className="p-16 text-center text-muted-foreground">
              <Loader2 className="w-8 h-8 animate-spin mx-auto mb-2" /> Loading…
            </div>
          ) : filteredFiles.length === 0 && uploading.length === 0 ? (
            <div className="p-16 text-center cursor-pointer" onClick={() => fileInputRef.current?.click()}>
              <ImageIcon className="w-16 h-16 text-muted-foreground/30 mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-foreground mb-1">
                {search ? "No images match your search" : "Drag and drop your first image"}
              </h3>
              <p className="text-sm text-muted-foreground">
                {search ? "Try a different search term." : "Or click here to browse. Supports JPG, PNG, WebP up to 10MB."}
              </p>
            </div>
          ) : (
            <div className={cn("grid gap-3", isCompact ? "grid-cols-3 sm:grid-cols-4" : "grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5")}>
              {uploading.map((u) => (
                <div key={u.id} className="aspect-square rounded-lg border border-border bg-secondary/50 relative overflow-hidden">
                  <div className="absolute inset-0 flex flex-col items-center justify-center gap-2">
                    <Loader2 className="w-6 h-6 animate-spin text-primary" />
                    <span className="text-xs text-muted-foreground truncate max-w-[80%]">{u.name}</span>
                  </div>
                  <div className="absolute bottom-0 left-0 right-0 h-1 bg-secondary">
                    <div className="h-full bg-primary transition-all duration-300" style={{ width: `${u.progress}%` }} />
                  </div>
                </div>
              ))}

              {filteredFiles.map((file) => {
                const isSelected = selectedId === file.id;
                const isBulkSelected = bulkSelected.has(file.id);
                return (
                  <div
                    key={file.id}
                    onClick={() => {
                      if (bulkMode) toggleBulkSelect(file.id);
                      else setSelectedId(isSelected ? null : file.id);
                    }}
                    className={cn(
                      "aspect-square rounded-lg border-2 relative overflow-hidden cursor-pointer group transition-all",
                      isSelected || isBulkSelected ? "border-primary ring-2 ring-primary/20" : "border-border hover:border-primary/50"
                    )}
                  >
                    <img src={file.url} alt={file.alt_text || file.file_name} className="w-full h-full object-cover" loading="lazy" />
                    {(isSelected || isBulkSelected) && (
                      <div className="absolute top-2 right-2 w-6 h-6 rounded-full bg-primary flex items-center justify-center">
                        <Check className="w-3.5 h-3.5 text-primary-foreground" />
                      </div>
                    )}
                    {bulkMode && !isBulkSelected && (
                      <div className="absolute top-2 right-2 w-6 h-6 rounded-full border-2 border-background/80 bg-background/50" />
                    )}
                    <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-foreground/60 to-transparent p-2 opacity-0 group-hover:opacity-100 transition-opacity">
                      <p className="text-xs text-background truncate">{file.url_slug || file.file_name}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Sidebar */}
      {selectedFile && !bulkMode && (
        <div className={cn("bg-background rounded-xl border border-border p-5", isCompact ? "w-full lg:w-64" : "w-full lg:w-80 shrink-0")}>
          <FileDetailsSidebar
            file={selectedFile}
            onSave={saveFileMetadata}
            onClose={() => setSelectedId(null)}
            onDelete={(id) => setDeleteTarget(id)}
            onSelect={onSelect}
            mode={mode}
          />
        </div>
      )}

      {/* Delete Confirmation */}
      <AlertDialog open={!!deleteTarget} onOpenChange={() => setDeleteTarget(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete this file?</AlertDialogTitle>
            <AlertDialogDescription>This action cannot be undone. The file will be permanently removed from storage.</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={() => deleteTarget && handleDelete(deleteTarget)} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">Delete</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Bulk Delete */}
      <AlertDialog open={bulkDeleteOpen} onOpenChange={setBulkDeleteOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete {bulkSelected.size} file(s)?</AlertDialogTitle>
            <AlertDialogDescription>This action cannot be undone. All selected files will be permanently removed.</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleBulkDelete} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">Delete All</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

export default MediaLibrary;
