// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const PRODUCTION_SUPABASE_URL = 'https://xukkejkvcgixogvbllmf.supabase.co';

const isDev = import.meta.env.DEV;
const allowProdDataInDev = import.meta.env.VITE_ALLOW_PROD_DATA_IN_DEV === 'true';
const usingProductionSupabase = SUPABASE_URL === PRODUCTION_SUPABASE_URL;

if (isDev && usingProductionSupabase && !allowProdDataInDev) {
  throw new Error(
    [
      'Safety check blocked startup: localhost is configured to use production Supabase.',
      'To keep local changes local, point VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to a dev Supabase project in .env.local.',
      'If you intentionally want localhost to modify production data, set VITE_ALLOW_PROD_DATA_IN_DEV=true in .env.local.',
    ].join(' ')
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});